<?php

namespace App\Exports;

use App\Models\CFISModel;
use Illuminate\Database\Eloquent\Collection;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;

class CadidateReportExport implements FromCollection, WithHeadings
{
    protected $candidates;

    public function __construct(Collection $candidates)
    {
        $this->candidates = $candidates;
    }

    public function collection()
    {
        return $this->candidates->load('candidateDocuments', 'clientstate')->map(function ($candidate, $index) {

            $documentPaths = $candidate->candidateDocuments->pluck('path', 'name');
            // \Log::info('documents:', $documentPaths->toArray());

            return [
                'Sl No' => $index + 1,
                // 'Client ID' => $candidate->client_id,
                'Client Name' => $candidate->entity_name,
                'Console ID' => $candidate->console_id,
                'FFI Emp ID' => $candidate->ffi_emp_id,
                'Grade' => $candidate->grade,
                'Client Emp ID' => $candidate->client_emp_id,
                'Employee Name' => $candidate->emp_name,
                'Middle Name' => $candidate->middle_name,
                'Last Name' => $candidate->last_name,
                'Interview Date' => optional($candidate->interview_date)->format('d-m-Y'),
                'Joining Date' => optional($candidate->joining_date)->format('d-m-Y'),
                'Contract Date' => optional($candidate->contract_date)->format('d-m-Y'),
                'Status' => $candidate->status == 1 ? 'Active' : 'In-Active',
                'Employee Last Date' => $candidate->employee_last_date,
                'Designation' => $candidate->designation,
                'Department' => $candidate->department,
                'State' => optional($candidate->clientstate)->state_name,
                'Location' => $candidate->location,
                'Branch' => $candidate->branch,
                'Date of Birth' => optional($candidate->dob)->format('d-m-Y'),
                'Gender' => $candidate->gender == 1 ? 'Male' : 'Female',
                'Father Name' => $candidate->father_name,
                'Father DOB' => optional($candidate->father_dob)->format('d-m-Y'),
                'Father Aadhar No' => $candidate->father_aadhar_no,
                'Mother Name' => $candidate->mother_name,
                'Mother DOB' => optional($candidate->mother_dob)->format('d-m-Y'),
                'Mother Aadhar No' => $candidate->mother_aadhar_no,
                'Religion' => $candidate->religion,
                'Languages' => $candidate->languages,
                'Mother Tongue' => $candidate->mother_tongue,
                'Marital Status' => $candidate->maritial_status,
                'Emergency Contact No' => "'" . $candidate->emer_contact_no,
                'Emergency Name' => $candidate->emer_name,
                'Emergency Relation' => $candidate->emer_relation,
                'Spouse Name' => $candidate->spouse_name,
                'Spouse DOB' => optional($candidate->spouse_dob)->format('d-m-Y'),
                'Spouse Aadhar No' => $candidate->spouse_aadhar_no,
                'No of Children' => $candidate->no_of_childrens,
                'Blood Group' => $candidate->blood_group,
                'Qualification' => $candidate->qualification,
                'Phone 1' => "'" . $candidate->phone1,
                'Phone 2' => "'" . $candidate->phone2,
                'Email' => $candidate->email,
                'Official Email' => $candidate->official_mail_id,
                'Permanent Address' => $candidate->permanent_address,
                'Present Address' => $candidate->present_address,
                'PAN No' => "'" . $candidate->pan_no,
                'Aadhar No' => "'" . $candidate->aadhar_no,
                'Driving License No' => $candidate->driving_license_no,
                'Bank Name' => $candidate->bank_name,
                'Bank Account No' => "'" . $candidate->bank_account_no,
                'Bank IFSC Code' => $candidate->bank_ifsc_code,
                'UAN No' => "'" . $candidate->uan_no,
                'ESIC No' => "'" . $candidate->esic_no,
                'Basic Salary' => $candidate->basic_salary,
                'HRA' => $candidate->hra,
                'Conveyance' => $candidate->conveyance,
                'Medical Reimbursement' => $candidate->medical_reimbursement,
                'Special Allowance' => $candidate->special_allowance,
                'Other Allowance' => $candidate->other_allowance,
                'ST Bonus' => $candidate->st_bonus,
                'Gross Salary' => $candidate->gross_salary,
                'Employee PF' => $candidate->emp_pf,
                'Employee ESIC' => $candidate->emp_esic,
                'Employee LWF' => $candidate->lwf,
                'PT' => $candidate->pt,
                'Total Deduction' => $candidate->total_deduction,
                'Take Home' => $candidate->take_home,
                'Employer PF' => $candidate->employer_pf,
                'Employer ESIC' => $candidate->employer_esic,
                'Employer LWF' => $candidate->employee_lwf,
                'Mediclaim' => $candidate->mediclaim,
                'CTC' => $candidate->ctc,

                'Aadhar Doc' => $documentPaths->has('aadhar_path') ? asset($documentPaths['aadhar_path']) : ($candidate->aadhar_path ? asset($candidate->aadhar_path) : ''),
                'PAN Doc' => $documentPaths->has('pan_path') ? asset($documentPaths['pan_path']) : ($candidate->pan_path ? asset($candidate->pan_path) : ''),
                'Driving License Doc' => $documentPaths->has('driving_license_path') ? asset($documentPaths['driving_license_path']) : ($candidate->driving_license_path ? asset($candidate->driving_license_path) : ''),
                'Resume Doc' => $documentPaths->has('resume') ? asset($documentPaths['resume']) : ($candidate->resume ? asset($candidate->resume) : ''),
                'Voter ID Doc' => $documentPaths->has('voter_id') ? asset($documentPaths['voter_id']) : ($candidate->voter_id ? asset($candidate->voter_id) : ''),
                'Employee Form Doc' => $documentPaths->has('emp_form') ? asset($documentPaths['emp_form']) : ($candidate->emp_form ? asset($candidate->emp_form) : ''),
                'PF/ESIC Form Doc' => $documentPaths->has('pf_esic_form') ? asset($documentPaths['pf_esic_form']) : ($candidate->pf_esic_form ? asset($candidate->pf_esic_form) : ''),
                'Payslip Doc' => $documentPaths->has('payslip') ? asset($documentPaths['payslip']) : ($candidate->payslip ? asset($candidate->payslip) : ''),
                'Experience Letter Doc' => $documentPaths->has('exp_letter') ? asset($documentPaths['exp_letter']) : ($candidate->exp_letter ? asset($candidate->exp_letter) : ''),
                'PAN Declaration Doc' => $documentPaths->has('pan_declaration') ? asset($documentPaths['pan_declaration']) : ($candidate->pan_declaration ? asset($candidate->pan_declaration) : ''),

            ];
        });
    }
    public function headings(): array
    {
        return [
            'Sl No',
            // 'Client ID',
            'Client Name',
            'Console ID',
            'FFI Emp ID',
            'Grade',
            'Client Emp ID',
            'Employee Name',
            'Middle Name',
            'Last Name',
            'Interview Date',
            'Joining Date',
            'Contract Date',
            'Status',
            'Employee Last Date',
            'Designation',
            'Department',
            'State',
            'Location',
            'Branch',
            'Date of Birth',
            'Gender',
            'Father Name',
            'Father DOB',
            'Father Aadhar No',
            'Mother Name',
            'Mother DOB',
            'Mother Aadhar No',
            'Religion',
            'Languages',
            'Mother Tongue',
            'Marital Status',
            'Emergency Contact No',
            'Emergency Name',
            'Emergency Relation',
            'Spouse Name',
            'Spouse DOB',
            'Spouse Aadhar No',
            'No of Children',
            'Blood Group',
            'Qualification',
            'Phone 1',
            'Phone 2',
            'Email',
            'Official Email',
            'Permanent Address',
            'Present Address',
            'PAN No',
            'Aadhar No',
            'Driving License No',
            'Bank Name',
            'Bank Account No',
            'Bank IFSC Code',
            'UAN No',
            'ESIC No',
            'Basic Salary',
            'HRA',
            'Conveyance',
            'Medical Reimbursement',
            'Special Allowance',
            'Other Allowance',
            'ST Bonus',
            'Gross Salary',
            'Employee PF',
            'Employee ESIC',
            'Employee LWF',
            'PT',
            'Total Deduction',
            'Take Home',
            'Employer PF',
            'Employer ESIC',
            'Employer LWF',
            'Mediclaim',
            'CTC',
            'Aadhar Doc',
            'PAN Doc',
            'Driving License Doc',
            'Resume Doc',
            'Voter ID Doc',
            'Employee Form Doc',
            'PF/ESIC Form Doc',
            'Payslip Doc',
            'Experience Letter Doc',
            'PAN Declaration Doc',
        ];
    }
}
