<?php

namespace App\Exports;

use Carbon\Carbon;
use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;

class CandidateMasterExport implements FromCollection, WithHeadings
{
    protected $candidates;

    public function __construct($candidates)
    {
        $this->candidates = $candidates;
    }

    public function collection()
    {
        return new Collection($this->candidates->map(function ($candidate) {
            return [
                'ID'                  => $candidate->id,
                'Client ID'           => $candidate->client_id,
                'Entity Name'         => $candidate->entity_name,
                'Console ID'          => $candidate->console_id,
                'FFI Emp ID'          => $candidate->ffi_emp_id,
                'Grade'               => $candidate->grade,
                'Client Emp ID'       => $candidate->client_emp_id,
                'Employee Name'       => $candidate->emp_name,
                'Middle Name'         => $candidate->middle_name,
                'Last Name'           => $candidate->last_name,
                'Interview Date'      => Carbon::parse($candidate->interview_date)->format('d-m-Y'),
                'Joining Date'        => Carbon::parse($candidate->joining_date)->format('d-m-Y'),
                'Contract Date'       => Carbon::parse($candidate->contract_date)->format('d-m-Y'),
                'Designation'         => $candidate->designation,
                'Department'          => $candidate->department,
                'State'               => $candidate->state,
                'Location'            => $candidate->location,
                'Branch'              => $candidate->branch,
                'Date of Birth'       => Carbon::parse($candidate->dob)->format('d-m-Y'),
                'Gender'              => $candidate->gender,
                'Father Name'         => $candidate->father_name,
                'Father DOB'          => Carbon::parse($candidate->father_dob)->format('d-m-Y'),
                'Father Aadhar No'    => $candidate->father_aadhar_no,
                'Mother Name'         => $candidate->mother_name,
                'Mother DOB'          => Carbon::parse($candidate->mother_dob)->format('d-m-Y'),
                'Mother Aadhar No'    => $candidate->mother_aadhar_no,
                'Religion'            => $candidate->religion,
                'Languages'           => $candidate->languages,
                'Mother Tongue'       => $candidate->mother_tongue,
                'Marital Status'      => $candidate->maritial_status,
                'Emergency Contact No' => $candidate->emer_contact_no,
                'Emergency Name'      => $candidate->emer_name,
                'Emergency Relation'  => $candidate->emer_relation,
                'Spouse Name'         => $candidate->spouse_name,
                'Spouse DOB'          => Carbon::parse($candidate->spouse_dob)->format('d-m-Y'),
                'Spouse Aadhar No'    => $candidate->spouse_aadhar_no,
                'No of Children'      => $candidate->no_of_childrens,
                'Blood Group'         => $candidate->blood_group,
                'Qualification'       => $candidate->qualification,
                'Phone 1'             => $candidate->phone1,
                'Phone 2'             => $candidate->phone2,
                'Email'               => $candidate->email,
                'Official Email'      => $candidate->official_mail_id,
                'Permanent Address'   => $candidate->permanent_address,
                'Present Address'     => $candidate->present_address,
                'PAN No'              => $candidate->pan_no,
                'Aadhar No'           => $candidate->aadhar_no,
                'Driving License No'  => $candidate->driving_license_no,
                'Bank Name'           => $candidate->bank_name,
                'Bank Account No'     => $candidate->bank_account_no,
                'Bank IFSC Code'      => $candidate->bank_ifsc_code,
                'UAN No'              => $candidate->uan_no,
                'ESIC No'             => $candidate->esic_no,
                'Basic Salary'        => $candidate->basic_salary,
                'HRA'                 => $candidate->hra,
                'Conveyance'          => $candidate->conveyance,
                'Medical Reimbursement' => $candidate->medical_reimbursement,
                'Special Allowance'   => $candidate->special_allowance,
                'Other Allowance'     => $candidate->other_allowance,
                'ST Bonus'           => $candidate->st_bonus,
                'Gross Salary'        => $candidate->gross_salary,
                'Employee PF'         => $candidate->emp_pf,
                'Employee ESIC'       => $candidate->emp_esic,
                'PT'                  => $candidate->pt,
                'Total Deduction'     => $candidate->total_deduction,
                'Take Home'           => $candidate->take_home,
                'Employer PF'         => $candidate->employer_pf,
                'Employer ESIC'       => $candidate->employer_esic,
                'Mediclaim'           => $candidate->mediclaim,
                'CTC'                 => $candidate->ctc,
            ];
        }));
    }

    public function headings(): array
    {
        return [
            'ID',
            'Client ID',
            'Entity Name',
            'Console ID',
            'FFI Emp ID',
            'Grade',
            'Client Emp ID',
            'Employee Name',
            'Middle Name',
            'Last Name',
            'Interview Date',
            'Joining Date',
            'Contract Date',
            'Designation',
            'Department',
            'State',
            'Location',
            'Branch',
            'Date of Birth',
            'Gender',
            'Father Name',
            'Father DOB',
            'Father Aadhar No',
            'Mother Name',
            'Mother DOB',
            'Mother Aadhar No',
            'Religion',
            'Languages',
            'Mother Tongue',
            'Marital Status',
            'Emergency Contact No',
            'Emergency Name',
            'Emergency Relation',
            'Spouse Name',
            'Spouse DOB',
            'Spouse Aadhar No',
            'No of Children',
            'Blood Group',
            'Qualification',
            'Phone 1',
            'Phone 2',
            'Email',
            'Official Email',
            'Permanent Address',
            'Present Address',
            'PAN No',
            'Aadhar No',
            'Driving License No',
            'Bank Name',
            'Bank Account No',
            'Bank IFSC Code',
            'UAN No',
            'ESIC No',
            'Basic Salary',
            'HRA',
            'Conveyance',
            'Medical Reimbursement',
            'Special Allowance',
            'Other Allowance',
            'ST Bonus',
            'Gross Salary',
            'Employee PF',
            'Employee ESIC',
            'PT',
            'Total Deduction',
            'Take Home',
            'Employer PF',
            'Employer ESIC',
            'Mediclaim',
            'CTC',
        ];
    }
}
