<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;

class EmployeeExport implements FromCollection, WithHeadings
{
    protected $employee;

    public function __construct($employee)
    {
        $this->employee = $employee;
    }

    public function collection()
    {
        return collect([
            [
                'console_id' => $this->employee->console_id,
                'ffi_emp_id' => $this->employee->ffi_emp_id,
                'grade' => $this->employee->grade,
                'client_emp_id' => $this->employee->client_emp_id,
                'emp_name' => $this->employee->emp_name,
                'middle_name' => $this->employee->middle_name,
                'last_name' => $this->employee->last_name,
                'interview_date' => $this->employee->interview_date,
                'joining_date' => $this->employee->joining_date,
                'contract_date' => $this->employee->contract_date,
                'designation' => $this->employee->designation,
                'department' => $this->employee->department,
                'state' => $this->employee->state,
                'location' => $this->employee->location,
                'branch' => $this->employee->branch,
                'dob' => $this->employee->dob,
                'gender' => $this->employee->gender,
                'father_name' => $this->employee->father_name,
                'father_dob' => $this->employee->father_dob,
                'father_aadhar_no' => $this->employee->father_aadhar_no,
                'mother_name' => $this->employee->mother_name,
                'mother_dob' => $this->employee->mother_dob,
                'mother_aadhar_no' => $this->employee->mother_aadhar_no,
                'religion' => $this->employee->religion,
                'languages' => $this->employee->languages,
                'mother_tongue' => $this->employee->mother_tongue,
                'emer_contact_no' => $this->employee->emer_contact_no,
                'emer_name' => $this->employee->emer_name,
                'emer_relation' => $this->employee->emer_relation,
                'spouse_name' => $this->employee->spouse_name,
                'spouse_dob' => $this->employee->spouse_dob,
                'spouse_aadhar_no' => $this->employee->spouse_aadhar_no,
                'no_of_childrens' => $this->employee->no_of_childrens,
                'blood_group' => $this->employee->blood_group,
                'qualification' => $this->employee->qualification,
                'phone1' => $this->employee->phone1,
                'phone2' => $this->employee->phone2,
                'email' => $this->employee->email,
                'official_mail_id' => $this->employee->official_mail_id,
                'permanent_address' => $this->employee->permanent_address,
                'present_address' => $this->employee->present_address,
                'pan_no' => $this->employee->pan_no,
                'pan_path' => $this->employee->pan_path,
                'aadhar_no' => $this->employee->aadhar_no,
                'aadhar_path' => $this->employee->aadhar_path,
                'driving_license_no' => $this->employee->driving_license_no,
                'driving_license_path' => $this->employee->driving_license_path,
                'bank_name' => $this->employee->bank_name,
                'bank_account_no' => $this->employee->bank_account_no,
                'bank_ifsc_code' => $this->employee->bank_ifsc_code,
                'uan_no' => $this->employee->uan_no,
                'esic_no' => $this->employee->esic_no,
                'uan_status' => $this->employee->uan_status,
                'esic_status' => $this->employee->esic_status,
                'basic_salary' => $this->employee->basic_salary,
                'hra' => $this->employee->hra,
                'conveyance' => $this->employee->conveyance,
                'medical_reimbursement' => $this->employee->medical_reimbursement,
                'special_allowance' => $this->employee->special_allowance,
                'other_allowance' => $this->employee->other_allowance,
                'st_bonus' => $this->employee->st_bonus,
                'gross_salary' => $this->employee->gross_salary,
                'emp_pf' => $this->employee->emp_pf,
                'emp_esic' => $this->employee->emp_esic,
                'pt' => $this->employee->pt,
                'total_deduction' => $this->employee->total_deduction,
                'take_home' => $this->employee->take_home,
                'employer_pf' => $this->employee->employer_pf,
                'employer_esic' => $this->employee->employer_esic,
                'mediclaim' => $this->employee->mediclaim,
                'ctc' => $this->employee->ctc,
            ]
        ]);
    }

    public function headings(): array
    {
        return [
            'Console ID',
            'FFI Employee ID',
            'Grade',
            'Client Employee ID',
            'Employee Name',
            'Middle Name',
            'Last Name',
            'Interview Date',
            'Joining Date',
            'Contract Date',
            'Designation',
            'Department',
            'State',
            'Location',
            'Branch',
            'Date of Birth',
            'Gender',
            'Father Name',
            'Father DOB',
            'Father Aadhar No',
            'Mother Name',
            'Mother DOB',
            'Mother Aadhar No',
            'Religion',
            'Languages',
            'Mother Tongue',
            'Emergency Contact No',
            'Emergency Contact Name',
            'Emergency Relation',
            'Spouse Name',
            'Spouse DOB',
            'Spouse Aadhar No',
            'No. of Children',
            'Blood Group',
            'Qualification',
            'Phone 1',
            'Phone 2',
            'Personal Email',
            'Official Email',
            'Permanent Address',
            'Present Address',
            'PAN No',
            'PAN Path',
            'Aadhar No',
            'Aadhar Path',
            'Driving License No',
            'Driving License Path',
            'Bank Name',
            'Bank Account No',
            'Bank IFSC Code',
            'UAN No',
            'ESIC No',
            'UAN Status',
            'ESIC Status',
            'Basic Salary',
            'HRA',
            'Conveyance',
            'Medical Reimbursement',
            'Special Allowance',
            'Other Allowance',
            'ST Bonus',
            'Gross Salary',
            'Employee PF',
            'Employee ESIC',
            'Professional Tax (PT)',
            'Total Deductions',
            'Take Home Salary',
            'Employer PF',
            'Employer ESIC',
            'Mediclaim',
            'CTC',
        ];
    }
}
